FULL_LINE = "**********"
PARTIAL_LINE = "*........*"
NEW_LINE = "\n"

print(FULL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      PARTIAL_LINE + NEW_LINE +
      FULL_LINE)
