WRONG_ZIP_FILE_FORMAT = "| Wrong zip file format (should be like: EX#_FirsName_LastName_ID.zip)"
SHOULD_BE_SUBMITTED_ONLY_1_ZIP_FILE = "| Should submit only 1 zip file"
PYTHON_FILE_DOES_NOT_EXIST = "| Python file does not exist [%s]"
CANT_EXTRACT_ZIP_FILE = "| Can't extract zip file"

BAD_SUBMISSION_STRUCTURE = "| -10 Wrong submission structure "
CONST_IS_NOT_CAMELCASE = "| -2 Const should be written in camel case"
DIDNT_USE_CONSTS = "| -2 You should use constants"
WRONG_OUTPUT = "| -5 Wrong output - Ex"
PROGRAM_FAILED = "| -5 Program failed - Ex"
